// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7hKZ26K9nNqGtBvjFS2GxaHQHa_Rse0',
    appId: '1:679003613374:web:2e20e3e12dba434403d6ef',
    messagingSenderId: '679003613374',
    projectId: 'cs354finalproject-308d4',
    authDomain: 'cs354finalproject-308d4.firebaseapp.com',
    storageBucket: 'cs354finalproject-308d4.appspot.com',
    measurementId: 'G-031BMGRH12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    //apiKey: 'AIzaSyAF6_uGwe3nRGqIvbFhAO7jX7_4b1fJcac',
    apiKey: 'AIzaSyCWm-Q0SWdtdnc9tZ46Wdo3R3hTVGgrx-M',
    appId: '1:679003613374:android:40f5cb3796fda3ed03d6ef',
    messagingSenderId: '679003613374',
    projectId: 'cs354finalproject-308d4',
    storageBucket: 'cs354finalproject-308d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    //apiKey: 'AIzaSyAULgbg5MaKZ7Mb3UwJPS8O3uUynrOMhR0',
    apiKey: 'AIzaSyCWm-Q0SWdtdnc9tZ46Wdo3R3hTVGgrx-M',
    appId: '1:679003613374:ios:e280a73cd949e20a03d6ef',
    messagingSenderId: '679003613374',
    projectId: 'cs354finalproject-308d4',
    storageBucket: 'cs354finalproject-308d4.appspot.com',
    iosClientId: '679003613374-ki3r3n3em1fale7cf5nrf4nif11j8bri.apps.googleusercontent.com',
    iosBundleId: 'com.dongyunyanjiusuo.cs354Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULgbg5MaKZ7Mb3UwJPS8O3uUynrOMhR0',
    appId: '1:679003613374:ios:e280a73cd949e20a03d6ef',
    messagingSenderId: '679003613374',
    projectId: 'cs354finalproject-308d4',
    storageBucket: 'cs354finalproject-308d4.appspot.com',
    iosClientId: '679003613374-ki3r3n3em1fale7cf5nrf4nif11j8bri.apps.googleusercontent.com',
    iosBundleId: 'com.dongyunyanjiusuo.cs354Project',
  );
}
